language: rust
cache: cargo
rust:
    - nightly
script:
    - cargo test --manifest-path=Cargo.toml

after_success:
    cargo doc --release && \
    /usr/bin/echo '<meta http-equiv=refresh content=0;url=YOURLIBNAME/index.html>' > target/doc/index.html && \
    ghp-import -p target/doc && \
